modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"

[[mods]]
modId="gh_farming_overhaul"
version="0.0.1"
displayName="Farming Overhaul Subpack"
description='''
Farming Overhaul Subpack for Grey Horizons RPG.
'''

[[dependencies.gh_farming_overhaul]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.gh_farming_overhaul]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"