package net.enderwish.TerraForma_Subpack.core.biome;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.biome.Biome;

/**
 * GHBiomes
 *
 * Resource keys for all 15 TerraForma biomes.
 * All biome data lives in JSON files generated by GHBiomeProvider.
 * This class is purely a registry of keys for use in GHBiomeSource
 * and biome tag providers.
 */
public class GHBiomes {

    // ── Arctic ────────────────────────────────────────────────────────────────
    public static final ResourceKey<Biome> FROZEN_TUNDRA         = key("frozen_tundra");
    public static final ResourceKey<Biome> GLACIAL_PEAKS         = key("glacial_peaks");

    // ── Temperate ─────────────────────────────────────────────────────────────
    public static final ResourceKey<Biome> TEMPERATE_FOREST      = key("temperate_forest");
    public static final ResourceKey<Biome> HIGHLAND_ORCHARD      = key("highland_orchard");
    public static final ResourceKey<Biome> ROLLING_MEADOWS       = key("rolling_meadows");
    public static final ResourceKey<Biome> BIRCH_HIGHLANDS       = key("birch_highlands");
    public static final ResourceKey<Biome> WETLANDS              = key("wetlands");

    // ── Mediterranean ─────────────────────────────────────────────────────────
    public static final ResourceKey<Biome> MEDITERRANEAN_SCRUBLAND = key("mediterranean_scrubland");
    public static final ResourceKey<Biome> COASTAL_CLIFFS         = key("coastal_cliffs");

    // ── Tropical ──────────────────────────────────────────────────────────────
    public static final ResourceKey<Biome> TROPICAL_RAINFOREST   = key("tropical_rainforest");
    public static final ResourceKey<Biome> MANGROVE_COAST        = key("mangrove_coast");
    public static final ResourceKey<Biome> VOLCANIC_LOWLANDS     = key("volcanic_lowlands");

    // ── Wasteland ─────────────────────────────────────────────────────────────
    public static final ResourceKey<Biome> ASH_PLAINS            = key("ash_plains");
    public static final ResourceKey<Biome> CRACKED_BADLANDS      = key("cracked_badlands");
    public static final ResourceKey<Biome> OVERGROWN_RUINS       = key("overgrown_ruins");

    // ── Helper ────────────────────────────────────────────────────────────────
    private static ResourceKey<Biome> key(String name) {
        return ResourceKey.create(Registries.BIOME,
                ResourceLocation.fromNamespaceAndPath(
                        "gh_terraforma", name));
    }
}
